### ISSUE TITLE
myjenkins/seed.groovy is no longer executed at startup

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-jenkins#162]
Probably some Jenkins plugins disappeared?

**Comment by gmacario** [comment]
Found with `docker-compose logs -f` (easy-jenkins 6c3d9881ca3b1e4be2cbc176dfa5bb1f65da7f11)

```
...
myjenkins_1  | INFO: Started SSHD at port 41307
myjenkins_1  | Feb 22, 2017 12:40:27 PM jenkins.util.groovy.GroovyHookScript execute
myjenkins_1  | WARNING: Failed to run script file:/var/jenkins_home/init.groovy.d/seed.groovy
myjenkins_1  | org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
myjenkins_1  | /var/jenkins_home/init.groovy.d/seed.groovy: 47: unable to resolve class ExecuteDslScripts
myjenkins_1  |  @ line 47, column 31.
myjenkins_1  |    project.getBuildersList().add(new ExecuteDslScripts(
myjenkins_1  |                                  ^
myjenkins_1  |
myjenkins_1  | /var/jenkins_home/init.groovy.d/seed.groovy: 48: unable to resolve class ExecuteDslScripts.ScriptLocation
myjenkins_1  |  @ line 48, column 3.
myjenkins_1  |      new ExecuteDslScripts.ScriptLocation("false","mydsl/**/*.groovy",null),
myjenkins_1  |      ^
myjenkins_1  |
myjenkins_1  | 2 errors
myjenkins_1  |
myjenkins_1  |  at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
myjenkins_1  |  at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:946)
myjenkins_1  |  at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:593)
myjenkins_1  |  at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:542)
myjenkins_1  |  at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
myjenkins_1  |  at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
myjenkins_1  |  at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
myjenkins_1  |  at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
myjenkins_1  |  at groovy.lang.GroovyShell.evaluate(GroovyShell.java:584)
myjenkins_1  |  at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:136)
myjenkins_1  |  at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:127)
myjenkins_1  |  at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:110)
myjenkins_1  |  at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:41)
myjenkins_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
myjenkins_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
myjenkins_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
myjenkins_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
myjenkins_1  |  at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
myjenkins_1  |  at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
myjenkins_1  |  at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
myjenkins_1  |  at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
myjenkins_1  |  at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
myjenkins_1  |  at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
myjenkins_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
myjenkins_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
myjenkins_1  |  at java.lang.Thread.run(Thread.java:745)
myjenkins_1  |
myjenkins_1  | Feb 22, 2017 12:40:27 PM jenkins.util.groovy.GroovyHookScript execute
myjenkins_1  | INFO: Executing /var/jenkins_home/init.groovy.d/tcp-slave-agent-port.groovy
myjenkins_1  | Feb 22, 2017 12:40:27 PM jenkins.InitReactorRunner$1 onAttained
myjenkins_1  | INFO: Completed initialization
myjenkins_1  | Feb 22, 2017 12:40:27 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
...
```

**Comment by gmacario** [comment]
TODO: Try installing Jenkins [Job DSL Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Job+DSL+Plugin) (https://github.com/jenkinsci/job-dsl-plugin)

**Comment by gmacario** [comment]
From JENKINS_URL > Manage Jenkins > Manage Plugins > Available

* [x] Select plugin "Job DSL" (`job-dsl:1.58`), then click **Install without restart**
