### ISSUE TITLE
java.lang.LinkageError: Failed to resolve class se.diabol.jenkins.pipeline.portlet.DeliveryPipelineViewPortlet$DescriptorImpl

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-jenkins#163]
https://github.com/gmacario/easy-jenkins commit 6c3d9881ca3b1e4be2cbc176dfa5bb1f65da7f11

Excerpt from `docker-compose logs -f`

```
...
myjenkins_1  | INFO: initialize scriptler
myjenkins_1  | Feb 22, 2017 12:40:22 PM hudson.ExtensionFinder$GuiceFinder$SezpozModule configure
myjenkins_1  | WARNING: Failed to load se.diabol.jenkins.pipeline.portlet.DeliveryPipelineViewPortlet$DescriptorImpl
myjenkins_1  | java.lang.LinkageError: Failed to resolve class se.diabol.jenkins.pipeline.portlet.DeliveryPipelineViewPortlet$DescriptorImpl
myjenkins_1  |  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.resolve(ExtensionFinder.java:489)
myjenkins_1  |  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:506)
myjenkins_1  |  at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
myjenkins_1  |  at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
myjenkins_1  |  at com.google.inject.spi.Elements.getElements(Elements.java:110)
myjenkins_1  |  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
myjenkins_1  |  at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
myjenkins_1  |  at com.google.inject.Guice.createInjector(Guice.java:96)
myjenkins_1  |  at com.google.inject.Guice.createInjector(Guice.java:73)
myjenkins_1  |  at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:280)
myjenkins_1  |  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
myjenkins_1  |  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
myjenkins_1  |  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
myjenkins_1  |  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
myjenkins_1  |  at java.lang.Class.newInstance(Class.java:442)
myjenkins_1  |  at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
myjenkins_1  |  at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:634)
myjenkins_1  |  at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:609)
myjenkins_1  |  at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:472)
myjenkins_1  |  at hudson.ExtensionList.load(ExtensionList.java:365)
myjenkins_1  |  at hudson.ExtensionList.ensureLoaded(ExtensionList.java:303)
myjenkins_1  |  at hudson.ExtensionList.getComponents(ExtensionList.java:168)
myjenkins_1  |  at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1116)
myjenkins_1  |  at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:82)
myjenkins_1  |  at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
myjenkins_1  |  at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
myjenkins_1  |  at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
myjenkins_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
myjenkins_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
myjenkins_1  |  at java.lang.Thread.run(Thread.java:745)
myjenkins_1  | Caused by: java.lang.TypeNotPresentException: Type hudson.plugins.view.dashboard.DashboardPortlet not present
myjenkins_1  |  at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
myjenkins_1  |  at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
myjenkins_1  |  at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
myjenkins_1  |  at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
myjenkins_1  |  at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
myjenkins_1  |  at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
myjenkins_1  |  at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:90)
myjenkins_1  |  at java.lang.Class.getGenericSuperclass(Class.java:777)
myjenkins_1  |  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.resolve(ExtensionFinder.java:470)
myjenkins_1  |  ... 29 more
myjenkins_1  | Caused by: java.lang.ClassNotFoundException: hudson.plugins.view.dashboard.DashboardPortlet
myjenkins_1  |  at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1373)
myjenkins_1  |  at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
myjenkins_1  |  at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
myjenkins_1  |  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
myjenkins_1  |  at java.lang.Class.forName0(Native Method)
myjenkins_1  |  at java.lang.Class.forName(Class.java:348)
myjenkins_1  |  at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
myjenkins_1  |  ... 37 more
myjenkins_1  |
myjenkins_1  | Feb 22, 2017 12:40:24 PM jenkins.InitReactorRunner$1 onAttained
myjenkins_1  | INFO: Prepared all plugins
...
```

**Comment by gmacario** [comment]
As of 2018-06-22 the issue is no longer reproducible.

Closing
