### ISSUE TITLE
Cannot fetch git repository on stash.alm.mentorg.com using https

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-jenkins#176]
Excerpt from Scan Multibranch Pipeline Log:

```
Started
[Thu Mar 16 09:04:27 UTC 2017] Starting branch indexing...
 > git rev-parse --is-inside-work-tree # timeout=10
Setting origin to https://gmacario@stash.alm.mentorg.com/scm/~gmacario/cevt-rfq-system-overview-doc.git
 > git config remote.origin.url https://gmacario@stash.alm.mentorg.com/scm/~gmacario/cevt-rfq-system-overview-doc.git # timeout=10
Fetching & pruning origin...
Fetching upstream changes from origin
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/* --prune
ERROR: [Thu Mar 16 09:04:28 UTC 2017] Could not fetch branches from source b5a813be-f426-482e-bcc3-031ef87d25e0
hudson.plugins.git.GitException: Command "git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/* --prune" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://gmacario@stash.alm.mentorg.com/scm/~gmacario/cevt-rfq-system-overview-doc.git/': Failed to connect to stash.alm.mentorg.com port 443: Connection refused

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1793)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1519)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:64)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:315)
	at jenkins.plugins.git.AbstractGitSCMSource.doRetrieve(AbstractGitSCMSource.java:211)
	at jenkins.plugins.git.AbstractGitSCMSource.retrieve(AbstractGitSCMSource.java:242)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:300)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:210)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:628)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:255)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:154)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:967)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
[Thu Mar 16 09:04:28 UTC 2017] Finished branch indexing. Indexing took 0.23 sec
```

**Comment by gmacario** [comment]
Troubleshooting the issue 

```
gmacario@ies-genbld01-ub16:~/MYGIT/easy-jenkins$ docker exec -ti -u root easyjenkins_myjenkins_1 /bin/bash
root@88fa37c753b6:/#
```

After applying the suggested workaround to, the git server can be properly resolved

```
root@88fa37c753b6:/# ping -c4 stash.alm.mentorg.com
PING stash.alm.mentorg.com (134.86.102.222): 56 data bytes
64 bytes from 134.86.102.222: icmp_seq=0 ttl=55 time=131.942 ms
64 bytes from 134.86.102.222: icmp_seq=1 ttl=55 time=131.684 ms
64 bytes from 134.86.102.222: icmp_seq=2 ttl=55 time=131.558 ms
64 bytes from 134.86.102.222: icmp_seq=3 ttl=55 time=131.554 ms
--- stash.alm.mentorg.com ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 131.554/131.684/131.942/0.158 ms
root@88fa37c753b6:/#
```

Also connections to SSH are allowed

```
root@88fa37c753b6:/# telnet stash.alm.mentorg.com 22
Trying 134.86.102.222...
Connected to stash.alm.mentorg.com.
Escape character is '^]'.
SSH-1.99-OpenSSH_3.9p1
HELP

Protocol mismatch.
Connection closed by foreign host.
root@88fa37c753b6:/#
```

While connections via https are refused

```
root@88fa37c753b6:/# telnet stash.alm.mentorg.com 443
Trying 134.86.102.222...
telnet: Unable to connect to remote host: Connection refused
root@88fa37c753b6:/#
```

**Comment by ankmraobade** [comment]
Failed to connect to repository : Command "/usr/bin/java ls-remote -h https://github.com/PythonAwsBoto3/webapp.git HEAD" returned status code 1
