### ISSUE TITLE
docs: Instructions building-yocto-udooneo are broken

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-jenkins#196]
Following instructions at <https://github.com/gmacario/easy-jenkins/blob/master/docs/building-yocto-udooneo.md> results in a build failure.

Tested on easy-jenkins master on build-gmhome

* Linux itm-gmacario-w7 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* OS: Ubuntu 16.04.2 LTS
* Docker version 17.04.0-ce, build 4845c56
* docker-compose version 1.8.0-rc2, build c72c966

Excerpt from http://build-gmhome.solarma.it:9080/job/build_yocto_udooneo/1/console

```
Started by user Admin (build-gmhome)
[EnvInject] - Loading node environment variables.
Building in workspace /var/jenkins_home/workspace/build_yocto_udooneo
Cloning the remote Git repository
Cloning repository https://github.com/gmacario/genivi-demo-platform
...
Unable to find image 'alpine:3.2' locally
3.2: Pulling from library/alpine
0e4f5d92549a: Pulling fs layer
0e4f5d92549a: Verifying Checksum
0e4f5d92549a: Download complete
0e4f5d92549a: Pull complete
Digest: sha256:cbbda5d34003b6c916f7fcd4aaba46c2de47c229dfbd06c5849d163dcf99d35e
Status: Downloaded newer image for alpine:3.2
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "chdir to cwd (\"/var/jenkins_home/workspace/build_yocto_udooneo\") set in config.json failed: no such file or directory".
FATAL: Failed to run docker image
java.lang.RuntimeException: Failed to run docker image
	at com.cloudbees.jenkins.plugins.docker_build_env.Docker.runDetached(Docker.java:226)
	at com.cloudbees.jenkins.plugins.docker_build_env.DockerBuildWrapper.startBuildContainer(DockerBuildWrapper.java:202)
	at com.cloudbees.jenkins.plugins.docker_build_env.DockerBuildWrapper.setUp(DockerBuildWrapper.java:175)
	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Archiving artifacts
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by gmacario** [comment]
Fix via https://github.com/gmacario/easy-jenkins/commit/1b2234c987e56c0c6a608f1847a0ef448ec75898
