### ISSUE TITLE
docker-compose logs: WARNING: Failed to load com.tikal.jenkins.plugins.multijob.MultiJobBuildSelector

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-jenkins#84]
Excerpt from `docker-compose logs`:

```
myjenkins_1 | Mar 15, 2016 10:11:14 PM hudson.ExtensionFinder$Sezpoz _find
myjenkins_1 | WARNING: Failed to load com.tikal.jenkins.plugins.multijob.MultiJobBuildSelector
myjenkins_1 | java.lang.InstantiationException: java.lang.NoClassDefFoundError: hudson/plugins/copyartifact/BuildSelector
myjenkins_1 |   at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
myjenkins_1 |   at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:628)
myjenkins_1 |   at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:617)
myjenkins_1 |   at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:388)
myjenkins_1 |   at hudson.ExtensionList.load(ExtensionList.java:349)
myjenkins_1 |   at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
myjenkins_1 |   at hudson.ExtensionList.iterator(ExtensionList.java:156)
myjenkins_1 |   at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:381)
myjenkins_1 |   at hudson.ExtensionList.load(ExtensionList.java:349)
myjenkins_1 |   at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
myjenkins_1 |   at hudson.ExtensionList.getComponents(ExtensionList.java:167)
myjenkins_1 |   at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:185)
myjenkins_1 |   at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
myjenkins_1 |   at hudson.ExtensionList.iterator(ExtensionList.java:156)
myjenkins_1 |   at hudson.ExtensionList.get(ExtensionList.java:147)
myjenkins_1 |   at com.cloudbees.jenkins.GitHubPushTrigger$DescriptorImpl.get(GitHubPushTrigger.java:329)
myjenkins_1 |   at org.jenkinsci.plugins.github.migration.Migrator.migrate(Migrator.java:41)
myjenkins_1 |   at org.jenkinsci.plugins.github.GitHubPlugin.postInitialize(GitHubPlugin.java:39)
myjenkins_1 |   at hudson.PluginManager$2$1$2.run(PluginManager.java:403)
myjenkins_1 |   at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
myjenkins_1 |   at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
myjenkins_1 |   at jenkins.model.Jenkins$8.runTask(Jenkins.java:924)
myjenkins_1 |   at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
myjenkins_1 |   at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
myjenkins_1 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
myjenkins_1 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
myjenkins_1 |   at java.lang.Thread.run(Thread.java:745)
myjenkins_1 | Caused by: java.lang.NoClassDefFoundError: hudson/plugins/copyartifact/BuildSelector
myjenkins_1 |   at java.lang.ClassLoader.defineClass1(Native Method)
myjenkins_1 |   at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
myjenkins_1 |   at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1139)
myjenkins_1 |   at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:801)
myjenkins_1 |   at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
myjenkins_1 |   at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1366)
myjenkins_1 |   at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
myjenkins_1 |   at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
myjenkins_1 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
myjenkins_1 |   at java.lang.reflect.Method.invoke(Method.java:498)
myjenkins_1 |   at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
myjenkins_1 |   at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:86)
myjenkins_1 |   at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:1188)
myjenkins_1 |   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
myjenkins_1 |   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
myjenkins_1 |   at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
myjenkins_1 |   ... 26 more
```

**Comment by gmacario** [comment]
Upstream bug tracked in https://issues.jenkins-ci.org/browse/JENKINS-30327

> Solution:
> install this plugin : Copy Artifact Plugin (https://wiki.jenkins-ci.org/display/JENKINS/Copy+Artifact+Plugin)
> service jenkins restart

**Comment by gmacario** [comment]
As of 2018-06-22 the issue is no longer reproducible.

Closing
